Repository CheoCharm/MapZ-Server, pull requests merged in 2022-06, with the labels that each got.

#4 feat: erd 설계 구현
  src/main/java/com/cheocharm/MapZ/MapZApplication.java
  src/main/java/com/cheocharm/MapZ/agreement/AgreementEntity.java
  src/main/java/com/cheocharm/MapZ/common/BaseEntity.java
  src/main/java/com/cheocharm/MapZ/diary/domain/DiaryEntity.java
  src/main/java/com/cheocharm/MapZ/diary/domain/DiaryImageEntity.java
  src/main/java/com/cheocharm/MapZ/diary/domain/DiaryLikeEntity.java
  src/main/java/com/cheocharm/MapZ/group/domain/GroupEntity.java
  src/main/java/com/cheocharm/MapZ/user/domain/UserEntity.java
  src/main/java/com/cheocharm/MapZ/usergroup/InvitationStatus.java
  src/main/java/com/cheocharm/MapZ/usergroup/UserGroupEntity.java
  src/main/java/com/cheocharm/MapZ/usergroup/UserRole.java
Labels: Feat

#6 feat: Spring security Config 임시 설정
  src/main/java/com/cheocharm/MapZ/agreement/AgreementEntity.java
  src/main/java/com/cheocharm/MapZ/common/config/SecurityConfig.java
  src/main/java/com/cheocharm/MapZ/common/domain/BaseEntity.java
  src/main/java/com/cheocharm/MapZ/diary/domain/DiaryEntity.java
  src/main/java/com/cheocharm/MapZ/diary/domain/DiaryImageEntity.java
  src/main/java/com/cheocharm/MapZ/diary/domain/DiaryLikeEntity.java
  src/main/java/com/cheocharm/MapZ/group/domain/GroupEntity.java
  src/main/java/com/cheocharm/MapZ/user/domain/UserEntity.java
  src/main/java/com/cheocharm/MapZ/usergroup/UserGroupEntity.java
Labels: Feat

#10 feat: querydsl 설정
  build.gradle
Labels: Feat

#14 hotfix: @JoinColumn 어노테이션 추가 및 unique 활성화
  src/main/java/com/cheocharm/MapZ/diary/domain/DiaryEntity.java
  src/main/java/com/cheocharm/MapZ/diary/domain/DiaryImageEntity.java
  src/main/java/com/cheocharm/MapZ/diary/domain/DiaryLikeEntity.java
  src/main/java/com/cheocharm/MapZ/group/domain/GroupEntity.java
  src/main/java/com/cheocharm/MapZ/user/domain/UserEntity.java
  src/main/java/com/cheocharm/MapZ/usergroup/UserGroupEntity.java
Labels: Hotfix

#16 hotfix: @AttributeOverride 삭제 및 테이블, 컬럼명 수정
  src/main/java/com/cheocharm/MapZ/agreement/AgreementEntity.java
  src/main/java/com/cheocharm/MapZ/diary/domain/DiaryEntity.java
  src/main/java/com/cheocharm/MapZ/diary/domain/DiaryImageEntity.java
  src/main/java/com/cheocharm/MapZ/diary/domain/DiaryLikeEntity.java
  src/main/java/com/cheocharm/MapZ/group/domain/GroupEntity.java
  src/main/java/com/cheocharm/MapZ/user/domain/UserEntity.java
  src/main/java/com/cheocharm/MapZ/usergroup/UserGroupEntity.java
Labels: Hotfix

#18 feat: logback-spring.xml 설정
  src/main/resources/logback-spring.xml
Labels: Feat

#17 feat: JWT 토큰 발행 기능 구현 및 시큐리티 필터 추가
  build.gradle
  src/main/java/com/cheocharm/MapZ/common/config/AuthenticationEntryPointCustom.java
  src/main/java/com/cheocharm/MapZ/common/config/SecurityConfig.java
  src/main/java/com/cheocharm/MapZ/common/jwt/JwtAuthenticationFilter.java
  src/main/java/com/cheocharm/MapZ/common/jwt/JwtAuthenticationUtils.java
  src/main/java/com/cheocharm/MapZ/common/jwt/JwtCommonUtils.java
  src/main/java/com/cheocharm/MapZ/common/jwt/JwtCreateUtils.java
  src/main/java/com/cheocharm/MapZ/user/domain/repository/UserRepository.java
Labels: Feat

#22 feat: ThreadLocal 구현
  src/main/java/com/cheocharm/MapZ/common/interceptor/AuthInterceptor.java
  src/main/java/com/cheocharm/MapZ/common/interceptor/UserThreadLocal.java
Labels: Feat

#24 feat: ExceptionHandling 구현
  src/main/java/com/cheocharm/MapZ/common/exception/CustomException.java
  src/main/java/com/cheocharm/MapZ/common/exception/ExceptionDetails.java
  src/main/java/com/cheocharm/MapZ/common/exception/GlobalExceptionHandler.java
Labels: Feat

#28 feat: AuthInterceptor 등록
  src/main/java/com/cheocharm/MapZ/common/config/WebConfig.java
  src/main/java/com/cheocharm/MapZ/common/interceptor/AuthInterceptor.java
Labels: Feat

#32 fix: ExceptionDetails에서 오류 type 제거
  src/main/java/com/cheocharm/MapZ/common/exception/ExceptionDetails.java
Labels: Fix

#33 feat: 구글 로그인 구현
  build.gradle
  src/main/java/com/cheocharm/MapZ/MapZApplication.java
  src/main/java/com/cheocharm/MapZ/common/config/SecurityConfig.java
  src/main/java/com/cheocharm/MapZ/common/config/WebConfig.java
  src/main/java/com/cheocharm/MapZ/common/exception/ExceptionDetails.java
  src/main/java/com/cheocharm/MapZ/common/exception/InvalidJwtException.java
  src/main/java/com/cheocharm/MapZ/common/jwt/JwtCreateUtils.java
  src/main/java/com/cheocharm/MapZ/common/oauth/GoogleYml.java
  src/main/java/com/cheocharm/MapZ/common/oauth/OauthApi.java
  src/main/java/com/cheocharm/MapZ/common/oauth/OauthUrl.java
  src/main/java/com/cheocharm/MapZ/common/util/ObjectMapperUtils.java
  src/main/java/com/cheocharm/MapZ/user/domain/UserController.java
  src/main/java/com/cheocharm/MapZ/user/domain/UserEntity.java
  src/main/java/com/cheocharm/MapZ/user/domain/UserService.java
  src/main/java/com/cheocharm/MapZ/user/domain/dto/GoogleIdTokenDto.java
  src/main/java/com/cheocharm/MapZ/user/domain/dto/TokenPairResponseDto.java
  src/main/java/com/cheocharm/MapZ/user/domain/dto/UserLoginDto.java
  src/main/java/com/cheocharm/MapZ/user/domain/dto/UserSignUpDto.java
Labels: Feat

#38 feat: 로그 구현
  src/main/java/com/cheocharm/MapZ/MapZApplication.java
  src/main/java/com/cheocharm/MapZ/common/CommonResponse.java
  src/main/java/com/cheocharm/MapZ/common/exception/ExceptionDetails.java
  src/main/java/com/cheocharm/MapZ/common/exception/FailConvertException.java
  src/main/java/com/cheocharm/MapZ/common/exception/GlobalExceptionHandler.java
  src/main/java/com/cheocharm/MapZ/common/exception/InternalServerException.java
  src/main/java/com/cheocharm/MapZ/common/exception/InvalidJwtException.java
  src/main/java/com/cheocharm/MapZ/common/log/exception/ExceptionLogAspect.java
  src/main/java/com/cheocharm/MapZ/common/log/exception/ExceptionLogSchema.java
  src/main/java/com/cheocharm/MapZ/common/log/response/ResponseLogAspect.java
  src/main/java/com/cheocharm/MapZ/common/log/response/ResponseLogSchema.java
  src/main/java/com/cheocharm/MapZ/diary/domain/DiaryController.java
  src/main/java/com/cheocharm/MapZ/group/domain/GroupController.java
Labels: Feat

#40 feat: 배포를 위해 Dockerfile 및 shell script 작성
  Dockerfile
  deploy.sh
Labels: Feat
