Repository CheoCharm/MapZ-Server, pull requests merged in 2022-08, with the labels that each got.

#76 feat: 그룹 나가기 API
  src/main/java/com/cheocharm/MapZ/common/exception/ExceptionDetails.java
  src/main/java/com/cheocharm/MapZ/common/exception/user/ExitGroupChiefException.java
  src/main/java/com/cheocharm/MapZ/diary/domain/DiaryEntity.java
  src/main/java/com/cheocharm/MapZ/diary/domain/respository/DiaryRepository.java
  src/main/java/com/cheocharm/MapZ/diary/domain/respository/DiaryRepositoryCustom.java
  src/main/java/com/cheocharm/MapZ/diary/domain/respository/DiaryRepositoryCustomImpl.java
  src/main/java/com/cheocharm/MapZ/group/domain/GroupController.java
  src/main/java/com/cheocharm/MapZ/group/domain/GroupService.java
  src/main/java/com/cheocharm/MapZ/group/domain/dto/ExitGroupDto.java
  src/main/java/com/cheocharm/MapZ/usergroup/UserGroupEntity.java
Labels: Feat

#79 feat: 회원가입 경로(제공자) 필드 추가
  src/main/java/com/cheocharm/MapZ/common/jwt/JwtAuthenticationUtils.java
  src/main/java/com/cheocharm/MapZ/common/jwt/JwtCommonUtils.java
  src/main/java/com/cheocharm/MapZ/common/jwt/JwtCreateUtils.java
  src/main/java/com/cheocharm/MapZ/group/domain/GroupService.java
  src/main/java/com/cheocharm/MapZ/user/domain/UserEntity.java
  src/main/java/com/cheocharm/MapZ/user/domain/UserProvider.java
  src/main/java/com/cheocharm/MapZ/user/domain/UserService.java
  src/main/java/com/cheocharm/MapZ/user/domain/repository/UserRepository.java
Labels: Fix, Feat

#80 feat: 그룹장 변경 API
  src/main/java/com/cheocharm/MapZ/group/domain/GroupController.java
  src/main/java/com/cheocharm/MapZ/group/domain/GroupService.java
  src/main/java/com/cheocharm/MapZ/group/domain/dto/ChangeChiefDto.java
  src/main/java/com/cheocharm/MapZ/usergroup/UserGroupEntity.java
Labels: Feat

#84 feat: 유저 검색 페이징
  src/main/java/com/cheocharm/MapZ/common/config/WebConfig.java
  src/main/java/com/cheocharm/MapZ/common/util/PagingUtils.java
  src/main/java/com/cheocharm/MapZ/user/domain/UserController.java
  src/main/java/com/cheocharm/MapZ/user/domain/UserService.java
  src/main/java/com/cheocharm/MapZ/user/domain/dto/GetUserListDto.java
  src/main/java/com/cheocharm/MapZ/user/domain/repository/UserRepository.java
  src/main/java/com/cheocharm/MapZ/user/domain/repository/UserRepositoryCustom.java
  src/main/java/com/cheocharm/MapZ/user/domain/repository/UserRepositoryCustomImpl.java
Labels: Feat

#88 feat: 다이어리 좋아요 API
  src/main/java/com/cheocharm/MapZ/common/exception/ExceptionDetails.java
  src/main/java/com/cheocharm/MapZ/common/exception/FailConvertException.java
  src/main/java/com/cheocharm/MapZ/common/exception/diary/AlreadyLikedDiaryException.java
  src/main/java/com/cheocharm/MapZ/common/exception/diary/NotFoundDiaryException.java
  src/main/java/com/cheocharm/MapZ/diary/domain/DiaryController.java
  src/main/java/com/cheocharm/MapZ/diary/domain/DiaryLikeEntity.java
  src/main/java/com/cheocharm/MapZ/diary/domain/DiaryService.java
  src/main/java/com/cheocharm/MapZ/diary/domain/dto/LikeDiaryDto.java
  src/main/java/com/cheocharm/MapZ/diary/domain/respository/DiaryLikeRepository.java
Labels: Feat

#91 feat: refreshToken으로 accessToken 발급
  src/main/java/com/cheocharm/MapZ/common/jwt/JwtCreateUtils.java
  src/main/java/com/cheocharm/MapZ/user/domain/UserController.java
Labels: Feat

#93 feat: 유저 그룹 초대 API
  src/main/java/com/cheocharm/MapZ/group/domain/GroupController.java
  src/main/java/com/cheocharm/MapZ/group/domain/GroupService.java
  src/main/java/com/cheocharm/MapZ/group/domain/dto/InviteUserListDto.java
  src/main/java/com/cheocharm/MapZ/user/domain/repository/UserRepositoryCustom.java
  src/main/java/com/cheocharm/MapZ/user/domain/repository/UserRepositoryCustomImpl.java
Labels: Feat

#95 fix: GET요청 시 querystring으로 데이터 받기
  src/main/java/com/cheocharm/MapZ/common/config/WebConfig.java
  src/main/java/com/cheocharm/MapZ/common/exception/ExceptionDetails.java
  src/main/java/com/cheocharm/MapZ/common/exception/GlobalExceptionHandler.java
  src/main/java/com/cheocharm/MapZ/group/domain/GroupController.java
  src/main/java/com/cheocharm/MapZ/group/domain/GroupService.java
  src/main/java/com/cheocharm/MapZ/group/domain/dto/GetGroupListDto.java
  src/main/java/com/cheocharm/MapZ/group/domain/dto/SearchGroupDto.java
  src/main/java/com/cheocharm/MapZ/user/domain/UserController.java
  src/main/java/com/cheocharm/MapZ/user/domain/UserService.java
  src/main/java/com/cheocharm/MapZ/user/domain/dto/CheckEmailDto.java
  src/main/java/com/cheocharm/MapZ/user/domain/dto/CheckPasswordDto.java
  src/main/java/com/cheocharm/MapZ/user/domain/dto/FindPasswordDto.java
  src/main/java/com/cheocharm/MapZ/user/domain/dto/GetNewPasswordDto.java
  src/main/java/com/cheocharm/MapZ/user/domain/dto/GetUserListDto.java
  src/main/java/com/cheocharm/MapZ/user/domain/dto/MapZSignInDto.java
  src/main/java/com/cheocharm/MapZ/user/domain/dto/MapZSignUpDto.java
Labels: Fix

#98 feat: 그룹 조회 정보 추가
  src/main/java/com/cheocharm/MapZ/common/CommonResponse.java
  src/main/java/com/cheocharm/MapZ/group/domain/GroupService.java
  src/main/java/com/cheocharm/MapZ/group/domain/dto/GetGroupListDto.java
Labels: Feat

#102 feat: 토큰 만료 상태코드 변경
  src/main/java/com/cheocharm/MapZ/common/CommonResponse.java
  src/main/java/com/cheocharm/MapZ/common/exception/ExceptionDetails.java
  src/main/java/com/cheocharm/MapZ/common/exception/GlobalExceptionHandler.java
Labels: Feat
