Repository CheoCharm/MapZ-Server, pull requests merged in 2022-07, with the labels that each got.

#43 fix: 배포 스크립트 수정 및 plain.jar 생성제한
  build.gradle
  deploy.sh
Labels: Fix

#45 feat: S3 설정
  build.gradle
  src/main/java/com/cheocharm/MapZ/common/config/S3Config.java
  src/main/java/com/cheocharm/MapZ/common/util/S3Utils.java
Labels: Feat, Gradle

#46 feat: S3 예외 설정
  src/main/java/com/cheocharm/MapZ/common/exception/ExceptionDetails.java
  src/main/java/com/cheocharm/MapZ/common/exception/S3/FailConvertToFileException.java
  src/main/java/com/cheocharm/MapZ/common/exception/S3/FailDeleteFileException.java
Labels: Feat

#47 feat: 그룹 생성, 조회 기능 구현
  src/main/java/com/cheocharm/MapZ/common/config/JpaAuditConfig.java
  src/main/java/com/cheocharm/MapZ/group/domain/GroupController.java
  src/main/java/com/cheocharm/MapZ/group/domain/GroupEntity.java
  src/main/java/com/cheocharm/MapZ/group/domain/GroupService.java
  src/main/java/com/cheocharm/MapZ/group/domain/dto/CreateGroupDto.java
  src/main/java/com/cheocharm/MapZ/group/domain/dto/GetGroupListDto.java
  src/main/java/com/cheocharm/MapZ/group/domain/repository/GroupRepository.java
  src/main/java/com/cheocharm/MapZ/usergroup/UserGroupEntity.java
  src/main/java/com/cheocharm/MapZ/usergroup/repository/UserGroupRepository.java
  src/main/java/com/cheocharm/MapZ/usergroup/repository/UserGroupRepositoryCustom.java
  src/main/java/com/cheocharm/MapZ/usergroup/repository/UserGroupRepositoryCustomImpl.java
Labels: Feat

#48 feat: 맵지 회원가입/로그인
  build.gradle
  src/main/java/com/cheocharm/MapZ/common/config/SecurityConfig.java
  src/main/java/com/cheocharm/MapZ/common/exception/ExceptionDetails.java
  src/main/java/com/cheocharm/MapZ/common/exception/GlobalExceptionHandler.java
  src/main/java/com/cheocharm/MapZ/common/exception/InvalidJwtException.java
  src/main/java/com/cheocharm/MapZ/common/exception/common/FailConvertToJsonException.java
  src/main/java/com/cheocharm/MapZ/common/exception/user/DuplicatedEmailException.java
  src/main/java/com/cheocharm/MapZ/common/exception/user/DuplicatedUsernameException.java
  src/main/java/com/cheocharm/MapZ/common/exception/user/InvalidJwtException.java
  src/main/java/com/cheocharm/MapZ/common/exception/user/NotFoundUserException.java
  src/main/java/com/cheocharm/MapZ/common/exception/user/WrongPasswordException.java
  src/main/java/com/cheocharm/MapZ/common/log/exception/ExceptionLogSchema.java
  src/main/java/com/cheocharm/MapZ/common/log/response/ResponseLogSchema.java
  src/main/java/com/cheocharm/MapZ/common/util/RandomUtils.java
  src/main/java/com/cheocharm/MapZ/user/domain/UserController.java
  src/main/java/com/cheocharm/MapZ/user/domain/UserEntity.java
  src/main/java/com/cheocharm/MapZ/user/domain/UserService.java
  src/main/java/com/cheocharm/MapZ/user/domain/dto/CheckEmailPasswordDto.java
  src/main/java/com/cheocharm/MapZ/user/domain/dto/MapZSignInDto.java
  src/main/java/com/cheocharm/MapZ/user/domain/dto/MapZSignUpDto.java
  src/main/java/com/cheocharm/MapZ/user/domain/repository/UserRepository.java
Labels: Feat

#53 feat: nginx 설정 및 배포스크립트 작성
  build.gradle
  deploy.sh
  nonstop.sh
Labels: Feat

#57 fix 배포 스크립트 수정
  nonstop.sh
Labels: Fix

#56 feat: 정보 제공 동의 기능 구현
  src/main/java/com/cheocharm/MapZ/agreement/AgreementEntity.java
  src/main/java/com/cheocharm/MapZ/agreement/repository/AgreementRepository.java
  src/main/java/com/cheocharm/MapZ/user/domain/UserEntity.java
  src/main/java/com/cheocharm/MapZ/user/domain/UserService.java
  src/main/java/com/cheocharm/MapZ/user/domain/dto/GoogleSignUpDto.java
  src/main/java/com/cheocharm/MapZ/user/domain/dto/MapZSignUpDto.java
Labels: Feat

#63 feat: 이메일, 비밀번호 유효성 검사 분리해서 진행
  src/main/java/com/cheocharm/MapZ/user/domain/UserController.java
  src/main/java/com/cheocharm/MapZ/user/domain/UserService.java
  src/main/java/com/cheocharm/MapZ/user/domain/dto/CheckEmailDto.java
  src/main/java/com/cheocharm/MapZ/user/domain/dto/CheckPasswordDto.java
Labels: Fix

#65 feat: Travis CI 설정 파일 작성
  .gitignore
  .travis.yml
Labels: Docs, Feat

#67 feat: 그룹 가입 신청 및 그룹 가입 신청상태 변경 API 구현
  src/main/java/com/cheocharm/MapZ/common/exception/ExceptionDetails.java
  src/main/java/com/cheocharm/MapZ/common/exception/usergroup/NotFoundUserGroupException.java
  src/main/java/com/cheocharm/MapZ/group/domain/GroupController.java
  src/main/java/com/cheocharm/MapZ/group/domain/GroupService.java
  src/main/java/com/cheocharm/MapZ/group/domain/dto/ChangeInvitationStatusDto.java
  src/main/java/com/cheocharm/MapZ/group/domain/dto/JoinGroupDto.java
  src/main/java/com/cheocharm/MapZ/usergroup/InvitationStatus.java
  src/main/java/com/cheocharm/MapZ/usergroup/UserGroupEntity.java
  src/main/java/com/cheocharm/MapZ/usergroup/repository/UserGroupRepository.java
Labels: Feat

#70 feat: 그룹생성 정규식 추가
  src/main/java/com/cheocharm/MapZ/group/domain/GroupService.java
  src/main/java/com/cheocharm/MapZ/group/domain/dto/CreateGroupDto.java
Labels: Fix, Feat

#73 feat: 그룹 검색 페이징 API
  src/main/java/com/cheocharm/MapZ/common/util/PagingUtils.java
  src/main/java/com/cheocharm/MapZ/common/util/QuerydslSupport.java
  src/main/java/com/cheocharm/MapZ/group/domain/GroupController.java
  src/main/java/com/cheocharm/MapZ/group/domain/GroupService.java
  src/main/java/com/cheocharm/MapZ/group/domain/dto/GetGroupListDto.java
  src/main/java/com/cheocharm/MapZ/group/domain/dto/SearchGroupDto.java
  src/main/java/com/cheocharm/MapZ/usergroup/repository/UserGroupRepositoryCustom.java
  src/main/java/com/cheocharm/MapZ/usergroup/repository/UserGroupRepositoryCustomImpl.java
Labels: Feat

#74 refactor: multipart 검증 방식 변경
  src/main/java/com/cheocharm/MapZ/user/domain/UserService.java
Labels: Refactor
