Repository CheoCharm/MapZ-Server, pull requests merged in 2023-01, with the labels that each got.

#136 feat: 그룹 멤버조회 API userId 필드 추가, refactor: UserGroupEntity 조회 로직 개선
  src/main/java/com/cheocharm/MapZ/group/domain/GroupService.java
  src/main/java/com/cheocharm/MapZ/group/domain/dto/GroupMemberDto.java
  src/main/java/com/cheocharm/MapZ/user/domain/UserController.java
  src/main/java/com/cheocharm/MapZ/user/domain/UserService.java
  src/main/java/com/cheocharm/MapZ/usergroup/repository/UserGroupRepositoryCustom.java
  src/main/java/com/cheocharm/MapZ/usergroup/repository/UserGroupRepositoryCustomImpl.java
Labels: Fix, Feat, Refactor

#140 test: Repository 클래스 테스트 코드 작성
  src/main/java/com/cheocharm/MapZ/group/domain/repository/GroupRepositoryCustom.java
  src/test/java/com/cheocharm/MapZ/IntegrationTest.java
  src/test/java/com/cheocharm/MapZ/RepositoryTest.java
  src/test/java/com/cheocharm/MapZ/group/domain/repository/GroupRepositoryCustomImplTest.java
  src/test/java/com/cheocharm/MapZ/user/domain/repository/UserRepositoryCustomImplTest.java
  src/test/java/com/cheocharm/MapZ/usergroup/repository/UserGroupRepositoryCustomImplTest.java
Labels: Test

#142 feat: Security Config 수정, 일기 작성 및 조회
  build.gradle
  src/main/java/com/cheocharm/MapZ/common/config/AuthenticationEntryPointCustom.java
  src/main/java/com/cheocharm/MapZ/common/config/SecurityConfig.java
  src/main/java/com/cheocharm/MapZ/diary/domain/DiaryController.java
  src/main/java/com/cheocharm/MapZ/diary/domain/DiaryEntity.java
  src/main/java/com/cheocharm/MapZ/diary/domain/DiaryService.java
  src/main/java/com/cheocharm/MapZ/diary/domain/dto/GetDiaryListDto.java
  src/main/java/com/cheocharm/MapZ/diary/domain/dto/WriteDiaryDto.java
  src/main/java/com/cheocharm/MapZ/diary/domain/respository/DiaryRepositoryCustom.java
  src/main/java/com/cheocharm/MapZ/diary/domain/respository/DiaryRepositoryCustomImpl.java
Labels: Feat

#144 feat: 그룹에서 내보내기 API
  src/main/java/com/cheocharm/MapZ/common/config/SecurityConfig.java
  src/main/java/com/cheocharm/MapZ/common/exception/ExceptionDetails.java
  src/main/java/com/cheocharm/MapZ/common/exception/usergroup/SelfKickException.java
  src/main/java/com/cheocharm/MapZ/group/domain/GroupController.java
  src/main/java/com/cheocharm/MapZ/group/domain/GroupService.java
  src/main/java/com/cheocharm/MapZ/group/domain/dto/KickUserDto.java
  src/main/java/com/cheocharm/MapZ/usergroup/InvitationStatus.java
  src/main/java/com/cheocharm/MapZ/usergroup/UserGroupEntity.java
Labels: Feat

#145 Feat: 댓글 삭제
  src/main/java/com/cheocharm/MapZ/comment/domain/CommentController.java
  src/main/java/com/cheocharm/MapZ/comment/domain/CommentEntity.java
  src/main/java/com/cheocharm/MapZ/comment/domain/CommentService.java
  src/main/java/com/cheocharm/MapZ/comment/domain/dto/DeleteCommentDto.java
  src/main/java/com/cheocharm/MapZ/comment/domain/repository/CommentRepository.java
Labels: Feat

#147 hotfix: Spring Actuator 요청 인증
  src/main/java/com/cheocharm/MapZ/common/config/SecurityConfig.java
  src/test/java/com/cheocharm/MapZ/RepositoryTest.java
Labels: Hotfix

#149 feat: 도커 이미지 Pull 스크립트, 그룹 소개글 글자수 제한
  pull.sh
  src/main/java/com/cheocharm/MapZ/group/domain/dto/CreateGroupDto.java
Labels: Docs, Feat
