Repository CheoCharm/MapZ-Server, pull requests merged in 2023-02, with the labels that each got.

#153 feat: 내가 쓴 일기 및 좋아요한 일기 조회 API
  src/main/java/com/cheocharm/MapZ/common/config/SecurityConfig.java
  src/main/java/com/cheocharm/MapZ/common/util/PagingUtils.java
  src/main/java/com/cheocharm/MapZ/common/util/QuerydslSupport.java
  src/main/java/com/cheocharm/MapZ/diary/domain/DiaryController.java
  src/main/java/com/cheocharm/MapZ/diary/domain/DiaryService.java
  src/main/java/com/cheocharm/MapZ/diary/domain/dto/MyDiaryDto.java
  src/main/java/com/cheocharm/MapZ/diary/domain/dto/MyLikeDiaryDto.java
  src/main/java/com/cheocharm/MapZ/diary/domain/respository/DiaryLikeRepositoryCustom.java
  src/main/java/com/cheocharm/MapZ/diary/domain/respository/DiaryLikeRepositoryCustomImpl.java
  src/main/java/com/cheocharm/MapZ/diary/domain/respository/DiaryRepositoryCustom.java
  src/main/java/com/cheocharm/MapZ/diary/domain/respository/DiaryRepositoryCustomImpl.java
  src/main/java/com/cheocharm/MapZ/diary/domain/respository/vo/MyDiaryVO.java
  src/main/java/com/cheocharm/MapZ/diary/domain/respository/vo/MyLikeDiaryVO.java
Labels: Feat

#156 feat: 그룹 내보내기, 나가기, 정보변경 로직 추가
  src/main/java/com/cheocharm/MapZ/comment/domain/repository/CommentRepository.java
  src/main/java/com/cheocharm/MapZ/comment/domain/repository/CommentRepositoryCustom.java
  src/main/java/com/cheocharm/MapZ/comment/domain/repository/CommentRepositoryCustomImpl.java
  src/main/java/com/cheocharm/MapZ/common/config/SecurityConfig.java
  src/main/java/com/cheocharm/MapZ/common/exception/ExceptionDetails.java
  src/main/java/com/cheocharm/MapZ/common/exception/usergroup/NotAcceptedUserException.java
  src/main/java/com/cheocharm/MapZ/diary/domain/respository/DiaryLikeRepositoryCustom.java
  src/main/java/com/cheocharm/MapZ/diary/domain/respository/DiaryLikeRepositoryCustomImpl.java
  src/main/java/com/cheocharm/MapZ/diary/domain/respository/DiaryRepositoryCustom.java
  src/main/java/com/cheocharm/MapZ/diary/domain/respository/DiaryRepositoryCustomImpl.java
  src/main/java/com/cheocharm/MapZ/group/domain/GroupController.java
  src/main/java/com/cheocharm/MapZ/group/domain/GroupEntity.java
  src/main/java/com/cheocharm/MapZ/group/domain/GroupService.java
  src/main/java/com/cheocharm/MapZ/group/domain/dto/ChangeGroupInfoDto.java
  src/main/java/com/cheocharm/MapZ/usergroup/repository/UserGroupRepositoryCustomImpl.java
Labels: Feat

#159 refactor: 메서드네이밍, import 와일드카드 미사용, 비교연산 메서드 사용
  build.gradle
  src/main/java/com/cheocharm/MapZ/common/log/response/ResponseLogSchema.java
  src/main/java/com/cheocharm/MapZ/diary/domain/DiaryController.java
  src/main/java/com/cheocharm/MapZ/diary/domain/DiaryService.java
  src/main/java/com/cheocharm/MapZ/diary/domain/respository/DiaryLikeRepositoryCustomImpl.java
  src/main/java/com/cheocharm/MapZ/diary/domain/respository/DiaryRepositoryCustomImpl.java
  src/main/java/com/cheocharm/MapZ/group/domain/GroupController.java
  src/main/java/com/cheocharm/MapZ/group/domain/GroupService.java
  src/main/java/com/cheocharm/MapZ/group/domain/repository/GroupRepositoryCustomImpl.java
  src/main/java/com/cheocharm/MapZ/user/domain/UserController.java
  src/main/java/com/cheocharm/MapZ/user/domain/UserService.java
  src/main/java/com/cheocharm/MapZ/user/domain/repository/UserRepositoryCustomImpl.java
  src/main/java/com/cheocharm/MapZ/usergroup/repository/UserGroupRepositoryCustomImpl.java
Labels: Refactor

#160 feat: 게시글 신고 기능
  src/main/java/com/cheocharm/MapZ/common/config/SecurityConfig.java
  src/main/java/com/cheocharm/MapZ/common/exception/ExceptionDetails.java
  src/main/java/com/cheocharm/MapZ/common/exception/report/AlreadyReportedDiary.java
  src/main/java/com/cheocharm/MapZ/report/domain/ReportController.java
  src/main/java/com/cheocharm/MapZ/report/domain/ReportEntity.java
  src/main/java/com/cheocharm/MapZ/report/domain/ReportService.java
  src/main/java/com/cheocharm/MapZ/report/domain/dto/ReportDto.java
  src/main/java/com/cheocharm/MapZ/report/domain/repository/ReportRepository.java
Labels: Feat

#162 feat: 글쓰기 구현
  src/main/java/com/cheocharm/MapZ/common/config/SecurityConfig.java
  src/main/java/com/cheocharm/MapZ/common/util/S3Utils.java
  src/main/java/com/cheocharm/MapZ/diary/domain/DiaryController.java
  src/main/java/com/cheocharm/MapZ/diary/domain/DiaryEntity.java
  src/main/java/com/cheocharm/MapZ/diary/domain/DiaryImageEntity.java
  src/main/java/com/cheocharm/MapZ/diary/domain/DiaryService.java
  src/main/java/com/cheocharm/MapZ/diary/domain/dto/WriteDiaryRequest.java
  src/main/java/com/cheocharm/MapZ/diary/domain/dto/request/DeleteTempDiaryRequest.java
  src/main/java/com/cheocharm/MapZ/diary/domain/dto/request/WriteDiaryImageRequest.java
  src/main/java/com/cheocharm/MapZ/diary/domain/dto/response/WriteDiaryImageResponse.java
  src/main/java/com/cheocharm/MapZ/diary/domain/respository/DiaryImageRepository.java
  src/main/java/com/cheocharm/MapZ/diary/domain/respository/DiaryImageRepositoryCustom.java
  src/main/java/com/cheocharm/MapZ/diary/domain/respository/DiaryImageRepositoryCustomImpl.java
  src/main/java/com/cheocharm/MapZ/diary/domain/respository/DiaryLikeRepositoryCustomImpl.java
  src/main/java/com/cheocharm/MapZ/diary/domain/respository/DiaryRepositoryCustomImpl.java
Labels: Feat

#163 fix: s3 업로드 로직 변경
  src/main/java/com/cheocharm/MapZ/common/util/S3Utils.java
  src/main/java/com/cheocharm/MapZ/diary/domain/DiaryService.java
Labels: Fix

#168 fix: Throwable을 넘기지 않는 문제
  src/main/java/com/cheocharm/MapZ/common/exception/CustomException.java
  src/main/java/com/cheocharm/MapZ/common/exception/ExceptionDetails.java
  src/main/java/com/cheocharm/MapZ/common/exception/GlobalExceptionHandler.java
  src/main/java/com/cheocharm/MapZ/common/exception/common/FailJsonProcessException.java
  src/main/java/com/cheocharm/MapZ/common/exception/common/FailParseException.java
  src/main/java/com/cheocharm/MapZ/common/exception/common/InputStreamIOException.java
  src/main/java/com/cheocharm/MapZ/common/exception/jwt/InvalidJwtException.java
  src/main/java/com/cheocharm/MapZ/common/exception/jwt/JwtExpiredException.java
  src/main/java/com/cheocharm/MapZ/common/jwt/JwtAuthenticationUtils.java
  src/main/java/com/cheocharm/MapZ/common/util/S3Utils.java
  src/main/java/com/cheocharm/MapZ/diary/application/DiaryService.java
  src/main/java/com/cheocharm/MapZ/user/application/UserService.java
  src/main/java/com/cheocharm/MapZ/user/presentation/dto/request/MapZSignUpRequest.java
Labels: Fix

#170 fix: DB html 저장
  src/main/java/com/cheocharm/MapZ/diary/application/DiaryService.java
  src/main/java/com/cheocharm/MapZ/diary/domain/DiaryEntity.java
  src/main/java/com/cheocharm/MapZ/diary/presentation/controller/DiaryController.java
  src/main/java/com/cheocharm/MapZ/diary/presentation/dto/response/WriteDiaryResponse.java
Labels: Fix
